services:
  subtitle-api:
    build:
      context: ./subtitle-api
    ports:
      - "5005:5005"
    volumes:
      - ./subtitle-api:/app
      - ./subtitle-api/pdf:/pdf
    restart: unless-stopped

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n:/home/node/.n8n
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_TUNNEL_URL=http://localhost:5678
    restart: unless-stopped

volumes:
  shared-pdf:
